FROM chrishah/repeatmasker-maker:18

MAINTAINER <christoph.hahn@uni-graz.at>

WORKDIR /usr/src

#install perl modules required for maker
ENV PERL_MM_USE_DEFAULT=1
RUN cpan ISHIGAKI/DBD-SQLite-1.64.tar.gz && \
	cpan forks && \
	cpan forks::shared && \
	cpan File::Which && \
	cpan Perl::Unsafe::Signals && \
	cpan Bit::Vector && \
	cpan Inline::C && \
	cpan IO::All && \
	cpan IO::Prompt

#This is a real hack to get Bioperl 1.7.7 installed. The XML::DOM::XPath always acts up during the test
# so I just avoid it by not doint 'make test'
RUN wget https://cpan.metacpan.org/authors/id/M/MI/MIROD/XML-DOM-XPath-0.14.tar.gz && \
	tar xfz XML-DOM-XPath-0.14.tar.gz && \
	cd XML-DOM-XPath-0.14 && \
	sed -i 's/use encoding/use/' t/test_non_ascii.t && \
	perl Makefile.PL && \
	make && \
	make install && \
	cd .. && \
	rm -rf XML-DOM-XPath-0.14* && \
	cpan CJFIELDS/BioPerl-1.7.7.tar.gz

#create working directory and move to entrypoint
VOLUME /home/data
WORKDIR /home/data
