FROM chrishah/repeatmasker-maker:18

MAINTAINER <christoph.hahn@uni-graz.at>

WORKDIR /usr/src

#install perl modules required for maker
ENV PERL_MM_USE_DEFAULT=1
RUN cpan ISHIGAKI/DBD-SQLite-1.64.tar.gz && \
	cpan forks && \
	cpan forks::shared && \
	cpan File::Which && \
	cpan Perl::Unsafe::Signals && \
	cpan Bit::Vector && \
	cpan Inline::C && \
	cpan IO::All && \
	cpan IO::Prompt && \
	cpan BioPerl

#create working directory and move to entrypoint
VOLUME /home/data
WORKDIR /home/data
